### ISSUE TITLE
Is the flatpak install, downloading ALL the OCR languages intended ?

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [flathub/com.github.unrud.djpdf#111]
![image](https://github.com/flathub/com.github.unrud.djpdf/assets/13170204/6b559ff4-429f-4a3d-a17e-9baf33aab732)
I would have to suggest it to be opt-in, and not opt-out.
Have perhaps one English language at all time as a backup, but download the user detected language, for me, French. If the user wants to download more languages, then they can download the rest on flathub too.

**Comment by Unrud** [comment]
> I would have to suggest it to be opt-in, and not opt-out.

Only the languages shown in the screenshot are downloaded automatically. There are >150  more languages available.

> but download the user detected language, for me, 

Unfortunately this isn't possible. As a compromise, I have set to automatically download the most frequently used languages.

You can uninstall the languages you don't need.

**Comment by PoorPocketsMcNewHold** [comment]
Alright, I understand more now. Thanks for the answer.

-------- Message d'origine --------
